### ISSUE TITLE
Implement String.Chars for MIME correctly

### ISSUE THREAD

**Issue by NobbZ** [NobbZ/file_info#5]
Currently MIME-types that have arguments associated are not correctly converted into a String.

**Comment by d4rk5eed** [comment]
give an example please

**Comment by NobbZ** [comment]
I'm not quite sure what this means as well ;)

But `MimetypeParser.parse/1` does return a tuple `{type, subtype, args}`, and if there are args available, then `String.Chars` for it will be the following:

https://github.com/NobbZ/file_info/blob/master/lib/file_info/mime.ex#L36-L38
```exs
def to_string(%MIME{type: type, subtype: subtype, arguments: args}) do
  "#{type}/#{subtype}---ARGS CURRENTLY NOT SUPPORTED (#{args})---"
end
```

I think I have done it this way, because I am not ware of a MIME-type that has arguments, and until I do find one, I can't really implement that function correctly.

**Comment by NobbZ** [comment]
I found a defintion at least, this makes implementing the protocol easier:

https://www.w3.org/Protocols/rfc1341/4_Content-Type.html
